models = ['Boeing 747', 'Airbus A320', 'Boeing 777']
airlines = ['Delta', 'United', 'JetBlue', 'Southwest']
airport_distances = {
    ('JFK', 'SFO'): 6,
    ('JFK', 'LAX'): 7,
    ('JFK', 'ORD'): 3,
    ('JFK', 'MIA'): 3,
    ('JFK', 'DFW'): 3,
    ('SFO', 'JFK'): 6,  
    ('SFO', 'LAX'): 1,
    ('SFO', 'ORD'): 4,
    ('SFO', 'MIA'): 5,
    ('SFO', 'DFW'): 4,
    ('LAX', 'JFK'): 7,  
    ('LAX', 'SFO'): 1,
    ('LAX', 'ORD'): 4,
    ('LAX', 'MIA'): 5,
    ('LAX', 'DFW'): 3,
    ('ORD', 'JFK'): 3,  
    ('ORD', 'SFO'): 4,
    ('ORD', 'LAX'): 4,
    ('ORD', 'MIA'): 3,
    ('ORD', 'DFW'): 2,
    ('MIA', 'JFK'): 3,  
    ('MIA', 'SFO'): 5,
    ('MIA', 'LAX'): 5,
    ('MIA', 'ORD'): 3,
    ('MIA', 'DFW'): 2,
    ('DFW', 'JFK'): 3,  
    ('DFW', 'SFO'): 4,
    ('DFW', 'LAX'): 3,
    ('DFW', 'ORD'): 2,
    ('DFW', 'MIA'): 2,
}